function exportAllPlotsForCurrentSignal(app, tag)
    % tag: e.g. accel name or 'A_minus_B'

    prefix = app.FileNamePrefixField.Value;
    suffix = app.FileNameSuffixField.Value;

    base = sprintf('%s_%s_%s', prefix, tag, suffix);

    % PSD
    app.exportAxesSet( ...
        {app.axPSD_a; app.axCum_a; app.axPSD_v; app.axCum_v; app.axPSD_d; app.axCum_d}, ...
        {sprintf('%s_PSD_accel.png', base), ...
         sprintf('%s_CumRMS_accel.png', base), ...
         sprintf('%s_PSD_velocity.png', base), ...
         sprintf('%s_CumRMS_velocity.png', base), ...
         sprintf('%s_PSD_disp.png', base), ...
         sprintf('%s_CumRMS_disp.png', base)} );

    % Time detail
    app.exportAxesSet( ...
        {app.axTH_a; app.axRMS_a; app.axTH_v; app.axRMS_v; app.axTH_d; app.axRMS_d}, ...
        {sprintf('%s_TH_accel.png', base), ...
         sprintf('%s_RMS_accel.png', base), ...
         sprintf('%s_TH_velocity.png', base), ...
         sprintf('%s_RMS_velocity.png', base), ...
         sprintf('%s_TH_disp.png', base), ...
         sprintf('%s_RMS_disp.png', base)} );

    % Optional: FFT, spectrogram, band plots
    % app.exportAxesSet({app.axFFT_a; app.axFFT_v; app.axFFT_d}, {...});
    % app.exportAxesSet({app.axSpec}, {...});
end
