function params = getFFTParams(app)

    params = struct( ...
        'Nfft',          app.Nfft, ...
        'WindowLength',  app.WindowLength, ...
        'OverlapLength', app.OverlapLength, ...
        'WindowPct',     app.WindowPct, ...
        'OverlapPct',    app.OverlapPct );
end



