function showFilterSettingsDialog(app)
%SHOWFILTERSETTINGSDIALOG  Modal dialog for filtering settings.

d = uifigure('Name','Filter Settings', ...
             'WindowStyle','modal', ...
             'Position',[100 100 420 360]);

%% Detrend
DetrendCheckBox = uicheckbox(d, ...
    'Text','Detrend', ...
    'Value', app.DetrendEnabled, ...
    'Position',[20 300 120 22]);

%% Taper
TaperCheckBox = uicheckbox(d, ...
    'Text','Taper (5%)', ...
    'Value', app.TaperEnabled, ...
    'Position',[20 260 120 22]);

%% Highpass
HighpassCheckBox = uicheckbox(d, ...
    'Text','Highpass', ...
    'Value', app.HighpassEnabled, ...
    'Position',[20 220 120 22]);

uilabel(d,'Text','HP Freq (Hz):', ...
          'Position',[160 220 100 22]);

HighpassFreqField = uieditfield(d,'numeric', ...
    'Limits',[0 Inf], ...
    'Value', app.HighpassFreq, ...
    'Position',[260 220 80 22]);

uilabel(d,'Text','HP Order:', ...
          'Position',[160 190 100 22]);

HighpassOrderField = uieditfield(d,'numeric', ...
    'Limits',[1 10], ...
    'Value', app.HighpassOrder, ...
    'Position',[260 190 80 22]);

%% Lowpass
LowpassCheckBox = uicheckbox(d, ...
    'Text','Lowpass', ...
    'Value', app.LowpassEnabled, ...
    'Position',[20 150 120 22]);

uilabel(d,'Text','LP Freq (Hz):', ...
          'Position',[160 150 100 22]);

LowpassFreqField = uieditfield(d,'numeric', ...
    'Limits',[0 Inf], ...
    'Value', app.LowpassFreq, ...
    'Position',[260 150 80 22]);

uilabel(d,'Text','LP Order:', ...
          'Position',[160 120 100 22]);

LowpassOrderField = uieditfield(d,'numeric', ...
    'Limits',[1 10], ...
    'Value', app.LowpassOrder, ...
    'Position',[260 120 80 22]);

%% Reset Defaults
uibutton(d,'Text','Reset Defaults', ...
    'Position',[20 60 120 30], ...
    'ButtonPushedFcn', @(~,~) resetDefaults());

    function resetDefaults()
        DetrendCheckBox.Value = false;
        TaperCheckBox.Value = false;
        HighpassCheckBox.Value = false;
        LowpassCheckBox.Value = false;

        HighpassFreqField.Value = 1;
        LowpassFreqField.Value  = 2000;

        HighpassOrderField.Value = 4;
        LowpassOrderField.Value  = 4;
    end

%% OK / Cancel
uibutton(d,'Text','Cancel', ...
    'Position',[60 20 100 30], ...
    'ButtonPushedFcn', @(~,~) close(d));

uibutton(d,'Text','OK', ...
    'Position',[180 20 100 30], ...
    'ButtonPushedFcn', @(~,~) onOK());

    function onOK()
        app.DetrendEnabled  = DetrendCheckBox.Value;
        app.TaperEnabled    = TaperCheckBox.Value;

        app.HighpassEnabled = HighpassCheckBox.Value;
        app.HighpassFreq    = HighpassFreqField.Value;
        app.HighpassOrder   = HighpassOrderField.Value;

        app.LowpassEnabled  = LowpassCheckBox.Value;
        app.LowpassFreq     = LowpassFreqField.Value;
        app.LowpassOrder    = LowpassOrderField.Value;

        refreshAllPlots(app);
        close(d);
    end

end
