function updateStatusBar(app)
    app.StatusBarLabel.Text = sprintf( ...
        'Mode: %s | FFT: %d | Window: %.0f%% | Overlap: %.0f%% | Units: %s | Segment: %.2f–%.2f s', ...
        app.ProcessingMode, ...
        app.FFTSizeDropDown.Value, ...
        app.WindowPercentField.Value, ...
        app.OverlapPercentField.Value, ...
        app.AccelUnitsDropDown.Value, ...
        app.StartTimeField.Value, ...
        app.EndTimeField.Value);
end
