app.NfftDropDown = uidropdown(fftGrid, ...
    'Items', {'512','1024','2048','4096','8192','16384','32768','65536'}, ...
    'Value', '8192', ...
    'ValueChangedFcn', @(~,~) app.updateFFTParams());
app.NfftDropDown.Layout.Column = [1 2];

app.WindowPctField = uieditfield(fftGrid, 'numeric', ...
    'Value', 50, ...
    'Limits', [1 100], ...
    'ValueChangedFcn', @(~,~) app.updateFFTParams());

app.OverlapPctField = uieditfield(fftGrid, 'numeric', ...
    'Value', 50, ...
    'Limits', [0 99], ...
    'ValueChangedFcn', @(~,~) app.updateFFTParams());

