
app.FFTSettingsMenu = uimenu(app.ProcessingMenu, ...
    'Text','FFT Settings...', ...
    'MenuSelectedFcn', @(~,~) app.showFFTSettingsDialog());
app.PlotScaleDropDown = uidropdown(gl, ...
    'Items', {'Linear','Log','SemilogX','SemilogY'}, ...
    'Value', 'Linear', ...
    'ValueChangedFcn', @(~,~) app.refreshAllPlots());
