%% ------------------------------------------------------------
%  RIGHT PANE: TAB GROUP + PLOT PANELS
%% ------------------------------------------------------------

% Create the tab group inside the RightPane
app.RightTabGroup = uitabgroup(app.RightPane, ...
    'Units','normalized', ...
    'Position',[0 0 1 1]);

%% TIME TAB
app.TimeTab = uitab(app.RightTabGroup, 'Title','Time');
app.TimeHistoryPanel = uipanel(app.TimeTab, ...
    'Units','normalized', ...
    'Position',[0 0 1 1], ...
    'BorderType','none');

%% FFT TAB
app.FFTTab = uitab(app.RightTabGroup, 'Title','FFT');
app.FFTPanel = uipanel(app.FFTTab, ...
    'Units','normalized', ...
    'Position',[0 0 1 1], ...
    'BorderType','none');

%% SPECTROGRAM TAB
app.SpectrogramTab = uitab(app.RightTabGroup, 'Title','Spectrogram');
app.SpectrogramPanel = uipanel(app.SpectrogramTab, ...
    'Units','normalized', ...
    'Position',[0 0 1 1], ...
    'BorderType','none');

%% BAND-LIMITED TAB
app.BandTab = uitab(app.RightTabGroup, 'Title','Bands');
app.BandPanel = uipanel(app.BandTab, ...
    'Units','normalized', ...
    'Position',[0 0 1 1], ...
    'BorderType','none');

%% PSD TAB
app.PSDTab = uitab(app.RightTabGroup, 'Title','PSD');
app.PSDPanel = uipanel(app.PSDTab, ...
    'Units','normalized', ...
    'Position',[0 0 1 1], ...
    'BorderType','none');

%% BATCH TAB
app.BatchTab = uitab(app.RightTabGroup, 'Title','Batch');
app.BatchPanel = uipanel(app.BatchTab, ...
    'Units','normalized', ...
    'Position',[0 0 1 1], ...
    'BorderType','none');
